# Generated by Django 3.1.1 on 2020-11-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SayohatJoylar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('qisqa_tarif', models.CharField(max_length=200)),
                ('narx', models.IntegerField(default=0)),
            ],
        ),
    ]
