# Generated by Django 3.1.1 on 2020-11-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sayohatjoylar',
            name='rasm',
            field=models.ImageField(default=0, upload_to='rasmlar/sayohat_joylari_rasm'),
            preserve_default=False,
        ),
    ]
