# Generated by Django 3.1.1 on 2020-11-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_sayohatjoylar_rasm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sayohatjoylar',
            name='narx',
            field=models.IntegerField(),
        ),
    ]
