# Generated by Django 3.1.1 on 2020-11-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_auto_20201105_0524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Murojat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=17)),
                ('mavzu', models.CharField(max_length=100)),
                ('xabar', models.TextField()),
                ('sana', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='sayohatjoylar',
            options={'verbose_name_plural': 'Sayohat Joylari'},
        ),
    ]
