# Generated by Django 3.1.1 on 2020-11-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0004_auto_20201106_0543'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoyRoyxat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sana', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
